- hosts: all
  tasks:
    - include_vars: container-builder-vars.yaml

    - name: Push images to DockerHub
      block:
        - command: docker login -u {{ magnum_docker_login.user }} -p {{ magnum_docker_login.password }}
          no_log: True
          retries: 5
        - command: docker push {{ magnum_repository }}/{{ item.name }}:{{ item.tag }}
          with_items: "{{ magnum_images }}"
          retries: 10
        - command: docker push {{ magnum_repository }}/{{ item.name }}:{{ kubernetes_version_v1_11 }}
          with_items: "{{ kubernetes_images }}"
          retries: 10
        - command: docker push {{ magnum_repository }}/{{ item.name }}:{{ kubernetes_version_v1_12 }}
          with_items: "{{ kubernetes_images }}"
          retries: 10
        - command: docker push {{ magnum_repository }}/{{ item.name }}:{{ kubernetes_version_v1_13 }}
          with_items: "{{ kubernetes_images }}"
          retries: 10
        - command: docker push {{ magnum_repository }}/helm-client:{{ helm_version }}
          retries: 10
